import os


KEY = os.environ["KEY"]
SLACK_BOT_TOKEN = os.environ["SLACK_BOT_TOKEN"]
CHANNEL_ID = os.environ['CHANNEL_ID']
GCP_PROJECT_ID = os.environ['GCP_PROJECT_ID']
GCP_TOPIC_ID = os.environ['GCP_TOPIC_ID']
GOOGLE_APPLICATION_CREDENTIALS = os.environ['GOOGLE_APPLICATION_CREDENTIALS']
